DATASET:
  root_dataset: "./data/"
  root_dataset1: "./data_ADE/"
  list_train: "./data/training_medium.odgt"
  list_train1: "./data_ADE/training.odgt"
  list_val: "./data/validation_medium.odgt"
  num_class: 2
  imgSizes: (300,)
  imgMaxSize: 1000
  padding_constant: 8
  segm_downsampling_rate: 8
  random_flip: True

MODEL:
  arch_encoder: "resnet18dilated"
  arch_decoder: "ppm_deepsup"
  fc_dim: 512

TRAIN:
  batch_size_per_gpu: 2
  num_epoch: 120
  start_epoch: 0
  epoch_iters: 5000
  optim: "SGD"
  lr_encoder: 0.002
  lr_decoder: 0.002
  lr_pow: 0.9
  beta1: 0.9
  weight_decay: 1e-4
  deep_sup_scale: 0.4
  fix_bn: False
  workers: 16
  disp_iter: 20
  seed: 304

VAL:
  visualize: False
  checkpoint: "epoch_120.pth"

TEST:
  checkpoint: "epoch_120.pth"
  result: "./cglncgl-resnet18dilated-ppm_deepsup_multitask_attention_medium"

DIR: "ckpt/cglncgl-resnet18dilated-ppm_deepsup_multitask_attention_medium"
