DATASET:
  root_dataset: "./data/"
  list_train: "./data/training_hard.odgt"
  list_val: "./data/validation_hard.odgt"
  num_class: 2
  imgSizes: (300, 375, 450, 525, 600)
  imgMaxSize: 1000
  padding_constant: 8
  segm_downsampling_rate: 8
  random_flip: True

MODEL:
  arch_encoder: "mobilenetv2dilated"
  arch_decoder: "c1"
  fc_dim: 320

TRAIN:
  batch_size_per_gpu: 1
  num_epoch: 200
  start_epoch: 158
  epoch_iters: 1000
  optim: "SGD"
  lr_encoder: 0.000003
  lr_decoder: 0.000003
  lr_pow: 0.9
  beta1: 0.9
  weight_decay: 1e-4
  deep_sup_scale: 0.4
  fix_bn: False
  workers: 16
  disp_iter: 20

VAL:
  visualize: True
  checkpoint: "epoch_200.pth"

TEST:
  checkpoint: "epoch_200.pth"
  result: "./cglncgl_context3_base"

DIR: "ckpt/cglncgl_context3_base"
