DATASET:
  imgMaxSize: 1000
  imgSizes: (300, 375, 450, 525, 600)
  list_train: ./data/training_hard.odgt
  list_val: ./data/validation_hard.odgt
  num_class: 2
  padding_constant: 32
  random_flip: True
  root_dataset: ./data/
  segm_downsampling_rate: 4
DIR: ckpt/cglncgl_ade20k-hrnetv2-c1-new_data-hard-baseline
MODEL:
  arch_decoder: c1
  arch_encoder: hrnetv2
  disc: 
  fc_dim: 720
  weights_decoder: 
  weights_decoder1: 
  weights_encoder: 
TEST:
  batch_size: 1
  checkpoint: epoch_30.pth
  result: ./cglncgl_ade20k-hrnetv2-c1-new_data-hard-baseline
TRAIN:
  batch_size_per_gpu: 2
  beta1: 0.9
  deep_sup_scale: 0.4
  disp_iter: 20
  epoch_iters: 1000
  fix_bn: False
  lr_decoder: 0.02
  lr_encoder: 0.02
  lr_pow: 0.9
  num_epoch: 30
  optim: SGD
  seed: 304
  start_epoch: 17
  weight_decay: 0.0001
  workers: 16
VAL:
  batch_size: 1
  checkpoint: epoch_30.pth
  visualize: True
